/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BrickItem = IDL.Record({
  'qty' : IDL.Nat,
  'brickType' : IDL.Text,
});
export const AppInfo = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'version' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Metrics = IDL.Record({
  'totalOrders' : IDL.Nat,
  'bricksDispatched' : IDL.Nat,
  'orderClosed' : IDL.Nat,
  'totalPaidAmount' : IDL.Nat,
  'totalDueAmount' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'brickItems' : IDL.Vec(BrickItem),
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'paidAmount' : IDL.Nat,
  'totalBricks' : IDL.Nat,
  'dueAmount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(BrickItem),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'getAppInfo' : IDL.Func([], [AppInfo], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMetrics' : IDL.Func([], [Metrics], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMetrics' : IDL.Func([Metrics], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BrickItem = IDL.Record({ 'qty' : IDL.Nat, 'brickType' : IDL.Text });
  const AppInfo = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'version' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Metrics = IDL.Record({
    'totalOrders' : IDL.Nat,
    'bricksDispatched' : IDL.Nat,
    'orderClosed' : IDL.Nat,
    'totalPaidAmount' : IDL.Nat,
    'totalDueAmount' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'brickItems' : IDL.Vec(BrickItem),
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'paidAmount' : IDL.Nat,
    'totalBricks' : IDL.Nat,
    'dueAmount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(BrickItem),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'getAppInfo' : IDL.Func([], [AppInfo], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMetrics' : IDL.Func([], [Metrics], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMetrics' : IDL.Func([Metrics], [], []),
  });
};

export const init = ({ IDL }) => { return []; };