/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppInfo {
  'name' : string,
  'description' : string,
  'author' : string,
  'version' : string,
}
export interface BrickItem { 'qty' : bigint, 'brickType' : string }
export interface Metrics {
  'totalOrders' : bigint,
  'bricksDispatched' : bigint,
  'orderClosed' : bigint,
  'totalPaidAmount' : bigint,
  'totalDueAmount' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'brickItems' : Array<BrickItem>,
  'date' : string,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'address' : string,
  'phone' : string,
  'paidAmount' : bigint,
  'totalBricks' : bigint,
  'dueAmount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<BrickItem>,
      bigint,
      bigint,
      bigint,
      bigint,
    ],
    bigint
  >,
  'getAppInfo' : ActorMethod<[], AppInfo>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMetrics' : ActorMethod<[], Metrics>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMetrics' : ActorMethod<[Metrics], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];